windows_start_root: D:/wwwroot/gofy
linux_start_root: /home/wwwroot/gofy
mac_start_root: /Users/wwwroot/gofy

date:
  timezone: "Asia/Shanghai"

httpServer:
  host: "*"
  port: 8080
  pidFilePath: "app/server.pid"
  pidFilePerm: 0644
  logFilePath: "app/server.log"

daemonServer:
   pidFilePath: "daemon/server.pid"
   pidFilePerm: 0644
   logFilePath: "/dev/null"

cronServer:
  pidFilePath: "cron/server.pid"
  pidFilePerm: 0644
  logFilePath: "/dev/null"
  timeLocation: "Asia/Shanghai"

scriptServer:
  pidFilePath: "script/server.pid"
  pidFilePerm: 0644
  logFilePath: "/dev/null"

# Logger
logger:
  info:
    Filename: "app/storage/logs/info.log"
    MaxSize: 100
    MaxAge: 30
    MaxBackups: 3
    LocalTime: true
    Compress: true
  error:
    Filename: "app/storage/logs/error.log"
    MaxSize: 100
    MaxAge: 30
    MaxBackups: 3
    LocalTime: true
    Compress: true

requestLogger:
  info:
    Filename: "app/storage/logs/request.log"
    MaxSize: 100
    MaxAge: 30
    MaxBackups: 3
    LocalTime: true
    Compress: true

systemLogger:
  info:
    Filename: "app/storage/logs/system_info.log"
    MaxSize: 100
    MaxAge: 30
    MaxBackups: 3
    LocalTime: true
    Compress: true
  error:
    Filename: "app/storage/logs/system_error.log"
    MaxSize: 100
    MaxAge: 30
    MaxBackups: 3
    LocalTime: true
    Compress: true


database:
  user: "admin"
  password: "secret"
  name: "mydb"

features:
  - "auth"
  - "logging"