windows_work_root_dir: D:/wwwroot/gofy
linux_work_root_dir: /home/wwwroot/gofy
mac_work_root_dir: /Users/wwwroot/gofy

date:
  timezone: "Asia/Shanghai"

httpServer:
  host: "*"
  port: 8080
  pidFilePath: "app/server.pid"
  pidFilePerm: 0644
  logFilePath: "app/server.log"
  crontab:
    enableCron: true
    cronYamlFilePath: "/home/wwwroot/gofy/cron.yaml"

daemonServer:
   pidFilePath: "daemon/server.pid"
   pidFilePerm: 0644
   logFilePath: "/dev/null"

cronServer:
  pidFilePath: "cron/server.pid"
  pidFilePerm: 0644
  logFilePath: "/dev/null"
  timeLocation: "Asia/Shanghai"
  cronYamlFilePath: "/home/wwwroot/gofy/cron.yaml"
  cronTaskDatabaseDns: "root:root@galaxy1024@tcp(localhost:3306)/bingcool?charset=utf8mb4&parseTime=True&loc=Local"

scriptServer:
  pidFilePath: ""
  pidFilePerm: 0644
  logFilePath: "/dev/null"

# Logger
logger:
  info:
    Filename: "app/storage/logs/info.log"
    MaxSize: 100
    MaxAge: 30
    MaxBackups: 3
    LocalTime: true
    Compress: true
  error:
    Filename: "app/storage/logs/error.log"
    MaxSize: 100
    MaxAge: 30
    MaxBackups: 3
    LocalTime: true
    Compress: true

requestLogger:
  info:
    Filename: "app/storage/logs/request.log"
    MaxSize: 100
    MaxAge: 30
    MaxBackups: 3
    LocalTime: true
    Compress: true

systemLogger:
  info:
    Filename: "app/storage/logs/system_info.log"
    MaxSize: 100
    MaxAge: 30
    MaxBackups: 3
    LocalTime: true
    Compress: true
  error:
    Filename: "app/storage/logs/system_error.log"
    MaxSize: 100
    MaxAge: 30
    MaxBackups: 3
    LocalTime: true
    Compress: true


database:
  user: "admin"
  password: "secret"
  name: "mydb"

features:
  - "auth"
  - "logging"