// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.
// Code generated by github.com/bingcool/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCronTaskLog = "cron_task_log"

// CronTaskLog 定时任务表运行态日志
type CronTaskLog struct {
	ID int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`

	// 关联的cron_task_id
	CronID int64 `gorm:"column:cron_id;not null;comment:关联的cron_task_id" json:"cron_id"`

	// 每轮执行的批次id
	ExecBatchID string `gorm:"column:exec_batch_id;not null;comment:每轮执行的批次id" json:"exec_batch_id"`

	// 定时脚本执行时的进程pid
	Pid int32 `gorm:"column:pid;not null;comment:定时脚本执行时的进程pid" json:"pid"`

	// 执行任务项meta信息
	TaskItem string `gorm:"column:task_item;comment:执行任务项meta信息" json:"task_item"`

	// 运行态记录信息
	Message string `gorm:"column:message;comment:运行态记录信息" json:"message"`

	// 创建时间
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`

	// 修改时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:修改时间" json:"updated_at"`

	// 删除时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`
}

// TableName CronTaskLog's table name
func (*CronTaskLog) TableName() string {
	return TableNameCronTaskLog
}
